name: RV4 Flora Wikipedia Scraper
on:
  workflow_dispatch: # Manual trigger only
jobs:
  scrape-flora:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BLOG_DEPLOY_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Create db directory
        run: |
          mkdir -p FlaskApp/services/v4/db
          
      - name: Run Flora scraper
        run: |
          cd FlaskApp/services/v4
          python FloraWikipediaScraper.py
          
      - name: Move database to db folder
        run: |
          if [ -f FlaskApp/services/v4/flora_data.db ]; then
            mv FlaskApp/services/v4/flora_data.db FlaskApp/services/v4/db/flora_data.db
            echo "Database moved to db folder"
          else
            echo "Database file not found"
          fi
          
      - name: Check for database changes
        id: check_changes
        run: |
          if [ -f FlaskApp/services/v4/db/flora_data.db ]; then
            echo "Database file exists in db folder"
            git add FlaskApp/services/v4/db/flora_data.db
            if git diff --cached --quiet; then
              echo "changes=false" >> $GITHUB_OUTPUT
            else
              echo "changes=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "Database file not found in db folder"
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push database
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add FlaskApp/services/v4/db/flora_data.db
          git commit -m "Update flora database - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push
          
      - name: Upload database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flora-database-${{ github.run_number }}
          path: FlaskApp/services/v4/db/flora_data.db
          retention-days: 30
